### PR TITLE
feat: add propTypes check

### LINKED ISSUE #614: ESLint加上prop-types相關檢查
想加上`react/prop-types`, `react/no-unused-prop-types`
不知道是不是之前被拿掉，不過還是覺得加一下是不是比較好

### PR DESCRIPTION
**Pull request by mark86092**
！這個 PR 還需要大量修正

@peteranny 如果你也有開發修正 propTypes，也可以開 PR 送到 eslint-proptype branch，我們一起來把這一堆 errors 修掉

Close #614

## 這個 PR 是？ 

Component 加上 propTypes

propTypes 可以幫助開發者知道傳入 prop 的資料特性 (optional, required)，也可以幫助開發者拿取資料時更好認識資料結構

## 我應該如何手動測試？ 

- [ ] UT 跑過即可

### CODE REVIEW

**Comment by mark86092** [comment]
有看到 https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/sort-prop-types.md 有 `react/sort-prop-types` 這條規則

它可以自動排序 PropTypes 的字典順序，我覺得可以加上去 auto fix， @peteranny 覺得如何？

**Comment by peteranny** [comment]
> 有看到 https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/sort-prop-types.md 有 `react/sort-prop-types` 這條規則
> 
> 它可以自動排序 PropTypes 的字典順序，我覺得可以加上去 auto fix， @peteranny 覺得如何？

All for it

**Comment by mark86092** [comment]
@peteranny 這個 PR 已加上 sort-proptype

**Comment by mark86092** [comment]
大概可以分成底下三群

group 1: @mark86092 
- [ ] src/components/App/Header/Top/EmailVerificationTop.js
- [ ] src/components/App/Header/Top/index.js
- [ ] src/components/Buy/PaymentSection/Row.js
- [ ] src/components/Buy/PaymentSection/index.js
- [ ] src/components/Buy/SubscriptionsSection/Captain.js
- [ ] src/components/BuyResultPage/PaymentResult/Success.js

group 2
- [ ] src/components/CompanyAndJobTitle/IndexPage/index.js
- [ ] src/components/CompanyAndJobTitle/InterviewExperiences/ExperienceEntry.js
- [ ] src/components/CompanyAndJobTitle/InterviewExperiences/Helmet.js
- [ ] src/components/CompanyAndJobTitle/Overview/Helmet.js

group 3
- [ ] src/components/common/Questionnaire/ExpandedModal/ScoreRange/index.js
- [ ] src/components/common/Questionnaire/ExpandedModal/index.js
- [ ] src/components/common/Seo/SeoStructure.js
- [ ] src/components/common/TabLinkGroup/index.js
- [ ] src/components/common/base/Link.js
- [ ] src/components/common/base/Wrapper.js
- [ ] src/components/common/button/ButtonRect.js
- [ ] src/components/common/button/PrivateMessageButton.js
- [ ] src/components/common/form/TextInput/index.js
- [ ] src/containers/ShareExperience/SubmitAreaContainer.js

我先認領 group 1, @peteranny @barry800414 再麻煩了

**Comment by mark86092** [comment]
dev 的部分我會等 merge 的時候解，那個應該還好

**Comment by peteranny** [comment]
> 大概可以分成底下三群
> 
> group 1: @mark86092
> 
> * [x]  src/components/App/Header/Top/EmailVerificationTop.js
> * [x]  src/components/App/Header/Top/index.js
> * [x]  src/components/Buy/PaymentSection/Row.js
> * [x]  src/components/Buy/PaymentSection/index.js
> * [x]  src/components/Buy/SubscriptionsSection/Captain.js
> * [x]  src/components/BuyResultPage/PaymentResult/Success.js
> 
> group 2
> 
> * [ ]  src/components/CompanyAndJobTitle/IndexPage/index.js
> * [ ]  src/components/CompanyAndJobTitle/InterviewExperiences/ExperienceEntry.js
> * [ ]  src/components/CompanyAndJobTitle/InterviewExperiences/Helmet.js
> * [ ]  src/components/CompanyAndJobTitle/Overview/Helmet.js
> 
> group 3
> 
> * [ ]  src/components/common/Questionnaire/ExpandedModal/ScoreRange/index.js
> * [ ]  src/components/common/Questionnaire/ExpandedModal/index.js
> * [ ]  src/components/common/Seo/SeoStructure.js
> * [ ]  src/components/common/TabLinkGroup/index.js
> * [ ]  src/components/common/base/Link.js
> * [ ]  src/components/common/base/Wrapper.js
> * [ ]  src/components/common/button/ButtonRect.js
> * [ ]  src/components/common/button/PrivateMessageButton.js
> * [ ]  src/components/common/form/TextInput/index.js
> * [ ]  src/containers/ShareExperience/SubmitAreaContainer.js
> 
> 我先認領 group 1, @peteranny @barry800414 再麻煩了

我 group 3

**Comment by mark86092** [comment]
@peteranny 可以直接推到這個 branch 或是 PR到這個 branch 都行

**Comment by peteranny** [comment]
group 3 done

**Comment by peteranny** [comment]
@barry800414 我也處理 group 2 了

**Comment by mark86092** [comment]
@peteranny 感謝！

**Review by peteranny — APPROVED** [review]

**Comment by mark86092** [comment]
我也將這份改動 merge 進 dev 了（dev 基本上小修正就好了）

**Pull request merged**
