### PR TITLE
將舊版權限更新至新版權限API

### LINKED ISSUE #1006: [UI] 經驗單篇的解鎖進入點
[單篇-阻擋](https://hopk8t.axshare.com/#id=iz4xi8&p=%E5%96%AE%E7%AF%87_-_%E9%98%BB%E6%93%8B&g=1)
[單篇-解鎖成功](https://hopk8t.axshare.com/#id=76hjm3&p=%E5%96%AE%E7%AF%87_-_%E8%A7%A3%E9%8E%96%E6%88%90%E5%8A%9F&g=1)

### PR DESCRIPTION
**Pull request by peteranny**
#1006  

## 這個 PR 是？ 

Migrate to the modern pattern

## Dependency

- https://github.com/goodjoblife/WorkTimeSurvey-backend/issues/775

## 我應該如何手動測試？ 

到任何未解鎖的文章，會顯示未解鎖
到任何已解鎖的文章，會顯示已解鎖

### CODE REVIEW

**Comment by barry800414** [comment]
Also close #1014

**Review by WendellLiu — APPROVED** [review]
程式碼看起來沒什麼問題，如果測試也ＯＫ應該就沒問題了。

**Comment by barry800414** [comment]
It seems to me that there exists some issue:
graphql query shows hasPermission = true, however I still cannot see article

Screenshot 2023-04-07 at 12 09 41 AM
Screenshot 2023-04-07 at 12 08 57 AM
Screenshot 2023-04-07 at 12 08 51 AM

**Comment by barry800414** [comment]
After rebasing `dev` branch, I can get new UI, but still have no permission
Screenshot 2023-04-07 at 12 15 51 AM

**Comment by peteranny** [comment]
> It seems to me that there exists some issue: graphql query shows hasPermission = true, however I still cannot see article
> 
> Screenshot 2023-04-07 at 12 09 41 AM
> 
> Screenshot 2023-04-07 at 12 08 57 AM
> 
> Screenshot 2023-04-07 at 12 08 51 AM

感謝抓錯！新的API跟原本的API原來還是有差異：舊版API允許 null token，新版不允許。另外在 parse response 也有寫錯的部分。以上皆已修正。

**Comment by peteranny** [comment]
> After rebasing `dev` branch, I can get new UI, but still have no permission

剛剛經過修正後，發現後端在登入理應有權限的帳號，回傳的 `hasAllPermission` 確實回傳 `false`。要請後端協助。

**Comment by barry800414** [comment]
> 剛剛經過修正後，發現後端在登入理應有權限的帳號，回傳的 hasAllPermission 確實回傳 false。要請後端協助。

想問你怎麼知道應該是要有權限的？ 我這邊目前測 ok

**Pull request merged**
