### PR TITLE
[API] 移除 /companies/search

### LINKED ISSUE #1239: [前端] 修改API：一頁一題式公司自動完成
分享經驗 > 公司名稱 > autocomplete

API更新為 Query.search_companies(query)
https://goodjoblife.atlassian.net/wiki/spaces/GJ/pages/44793857/Design+doc

### PR DESCRIPTION
**Pull request by peteranny**
Close #1239 #1240  

## 這個 PR 是？ 

移除舊版 `/companies/search`
改用 `Query.search_companies`

## Screenshots  

<table>
<tr>
<th>一頁一題公司名稱</th>
<td>

https://github.com/goodjoblife/GoodJobShare/assets/7566586/0b0a12fc-a96b-4c7f-b8d3-60d91078b101

</td>
</tr>
<tr>
<th>舊版面試表單</th>
<td>

https://github.com/goodjoblife/GoodJobShare/assets/7566586/65f7a08e-1e0e-4d5e-8104-4ed453250465

</td>
</tr>
<tr>
<th>公司表單</th>
<td>

https://github.com/goodjoblife/GoodJobShare/assets/7566586/5a823a2d-86c1-4b8e-b249-b8d885820181

</td>
</tr>
</table>

## 我應該如何手動測試？ 

測試以下autocomplete:
- [ ] 分享經驗 > 面試經驗 > 公司名稱
- [ ] /share/interview-one-page
- [ ] /share/work-experiences

### CODE REVIEW

**Review by barry800414 — APPROVED** [review]
tested, LGTM, @mark86092 may need your review as well

**Comment by barry800414** [comment]
@peteranny do you consider to merge it ?

**Comment by peteranny** [comment]
> @peteranny do you consider to merge it ?

Waiting for @mark86092's approval

**Comment by mark86092** [comment]
I will look the PR tomorrow

**Review by mark86092 — APPROVED** [review]

**Pull request merged**
